### ISSUE TITLE
Format css

### ISSUE THREAD

**Issue by Ksengine** [KsTGTeam/Beautify#2]
format the source code

**Comment by aditya28sarin** [comment]
Can you assign me on this issue?

**Comment by Ksengine** [comment]
:+1::+1::+1: @aditya28sarin

**Comment by Ksengine** [comment]
i had already added a github actions based formatter.It can format code finely. but raise errors.
see: https://github.com/KsTGTeam/Beautify/actions/runs/450165558/workflow

**Comment by aditya28sarin** [comment]
Hey, so how exactly do you want the css code to be formatted, could you specify? Like adding comments and what all?

**Comment by Ksengine** [comment]
> Hey, so how exactly do you want the css code to be formatted, could you specify? Like adding comments and what all?

It's better if you can fix my github lint action

**Comment by Ksengine** [comment]
Stale issue message
